[config]

[templates.cava]
input_path = '/home/duane/.config/matugen/templates/cava.conf'
output_path = '/home/duane/.config/cava/config'

[templates.thunderbird]
input_path = '/home/duane/.config/matugen/templates/thunderbird-userChrome.css'
output_path = '/home/duane/.thunderbird/a8f88me1.default-release/chrome/userChrome.css'

[templates.geany]
input_path = '/home/duane/.config/matugen/templates/geany.conf'
output_path = '/home/duane/.config/geany/colorschemes/dms-matugen.conf'

[templates.xresources]
input_path = '/home/duane/.config/matugen/templates/Xresources'
output_path = '/home/duane/.Xresources'

[templates.duane-gtk4]
input_path = '/home/duane/.config/matugen/templates/gtk-colors.css'
output_path = '/home/duane/.config/gtk-4.0/duane-colors.css'

[templates.duane-gtk3]
input_path = '/home/duane/.config/matugen/templates/gtk-colors.css'
output_path = '/home/duane/.config/gtk-3.0/duane-colors.css'

[templates.color-finder]
input_path = '/home/duane/.config/matugen/templates/dank-color-finder'
output_path = '/home/duane/color-files/colors.css'

[templates.kitty-color]
input_path = "~/.config/matugen/templates/kitty-colors.conf"
output_path = "~/.config/kitty/dank16-colors.conf"

[templates.dank-color-geany]
input_path = '/home/duane/.config/matugen/templates/templates.dank-color-geany'
output_path = '/home/duane/.config/geany/colorschemes/dank-color-geany.conf'
