[config]

[templates.cava]
input_path = '/home/duane/.config/matugen/templates/cava.conf'
output_path = '/home/duane/.config/cava/config'

[templates.thunderbird]
input_path = '/home/duane/.config/matugen/templates/thunderbird-userChrome.css'
output_path = '/home/duane/.thunderbird/a8f88me1.default-release/chrome/userChrome.css'

[templates.geany]
input_path = '/home/duane/.config/matugen/templates/geany.conf'
output_path = '/home/duane/.config/geany/colorschemes/dms-matugen.conf'

[templates.xresources]
input_path = '/home/duane/.config/matugen/templates/Xresources'
output_path = '/home/duane/.Xresources'
